<template>
  <aside class="side-container" :class="player">
    <h2>{{ player === 'player1' ? 'Red' : 'Blue' }}</h2>
    <div class="number-points">Score: {{ numberPoints }}</div>
    <div
      class="swap-card"
      @click="selectSwap"
      :aria-disabled="!isSwapAllowed"
      :class="{ isSelected: store.isSwapSelected }"
    >
      <strong>Overthrow</strong>
      <Swords />
    </div>
    <div class="swaps-left-container">
      <div
        v-for="i in 4"
        :key="i"
        :class="{
          filled: numberSwaps >= i,
          isBeingUsed: store.isSwapSelected && numberSwaps === i && isSwapAllowed,
        }"
      ></div>
    </div>
  </aside>
</template>

<script lang="ts" setup>
import { Swords } from 'lucide-vue-next'
import { useGameStore } from '@/stores/game'
import { computed } from 'vue'
const props = defineProps<{ player: 'player1' | 'player2' }>()
const store = useGameStore()
const numberSwaps = computed(() => (props.player === 'player1' ? store.swap1 : store.swap2))
const numberPoints = computed(() => store.getPoints(props.player))
const isSwapAllowed = computed(
  () =>
    numberSwaps.value > 0 &&
    ((props.player === 'player1' && store.isPlayer1Turn) ||
      (props.player === 'player2' && !store.isPlayer1Turn)),
)
const selectSwap = () => {
  if (!isSwapAllowed.value) {
    return
  }
  store.toggleSwapSelected()
}
</script>

<style scoped>
.player1 {
  --theme-color: var(--p-red-400);
}
.player2 {
  --theme-color: var(--p-blue-400);
}
h2,
.swap-card {
  color: var(--theme-color);
}
.number-points {
  color: var(--theme-color);
  font-weight: bold;
  margin-bottom: var(--space-large);
}
.swap-card {
  background-color: var(--secondary-surface);
  border: 1px solid var(--secondary-surface);
  border-radius: var(--p-border-radius-sm);
  padding: var(--space-large);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  gap: var(--space-small);
  cursor: pointer;
  transition-duration: 0.2s;
}

.swap-card[aria-disabled='false']:hover {
  border: 1px solid var(--theme-color);
}

.isSelected[aria-disabled='false'] svg {
  -webkit-animation: jello-horizontal 1.2s ease-in-out infinite both;
  animation: jello-horizontal 1.2s ease-in-out infinite both;
}

svg {
  height: 3em;
  width: 3em;
}

.swaps-left-container {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: var(--space-small);
  padding: var(--space-small);
  border-radius: var(--p-border-radius-sm);
  width: 100%;
  height: 2em;
}
.swaps-left-container div {
  border-radius: var(--p-border-radius-sm);
  background-color: var(--secondary-surface);
}
.swaps-left-container .filled {
  background-color: var(--theme-color);
}
.isBeingUsed {
  -webkit-animation: fade-to-used 2.4s ease-in-out infinite both;
  animation: fade-to-used 2.4s ease-in-out infinite both;
}

@-webkit-keyframes fade-to-used {
  0% {
    background-color: var(--theme-color);
  }
  50% {
    background-color: var(--secondary-surface);
  }
  100% {
    background-color: var(--theme-color);
  }
}
@keyframes fade-to-used {
  0% {
    background-color: var(--theme-color);
  }
  50% {
    background-color: var(--secondary-surface);
  }
  100% {
    background-color: var(--theme-color);
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2024-12-5 15:32:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation jello-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
    transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}
@keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
    transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}
</style>
